// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.data;

#nullable disable

namespace Server.Data.Migration
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("Shared.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailImgPath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "description of category 1",
                            Name = "Category 1",
                            ThumbnailImgPath = "uploads.placeholder.jpg"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "description of category 2",
                            Name = "Category 2",
                            ThumbnailImgPath = "uploads.placeholder.jpg"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "description of category 3",
                            Name = "Category 3",
                            ThumbnailImgPath = "uploads.placeholder.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
